import { Platform, StyleSheet } from 'react-native';
import { colours } from '../../../shared/theme/colours';
import { radius } from '../../../shared/theme/radius';
import { spacing } from '../../../shared/theme/spacing';
import { typography } from '../../../shared/theme/typography';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colours.surface },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 2,
    backgroundColor: colours.surface,
    gap: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colours.divider,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: radius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colours.surfaceMuted,
    borderWidth: 1,
    borderColor: colours.divider,
  },
  headerInfo: { flex: 1 },
  topBarTitle: { fontSize: typography.md, fontWeight: '700', color: colours.textOnLight },
  topBarSub: { fontSize: typography.xxs, color: colours.textSubtle, marginTop: 1 },
  body: { flex: 1, backgroundColor: colours.surface },
  list: { flex: 1 },
  listContent: { paddingHorizontal: spacing.md, paddingVertical: spacing.md, gap: spacing.sm },
  emptyWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: spacing.xxl },
  emptyText: { fontSize: typography.sm, color: colours.textSubtle, textAlign: 'center', marginTop: 8 },
  loaderWrap: { flex: 1, alignItems: 'center', justifyContent: 'center' },

  systemNotice: {
    alignItems: 'center',
    paddingVertical: spacing.xs,
  },
  systemNoticeText: {
    fontSize: typography.xxs,
    lineHeight: Platform.select({ web: 16, default: 30 }),
    fontStyle: 'italic',
    color: colours.textSubtle,
    textAlign: 'center',
  },

  bubbleRow: { flexDirection: 'row' },
  bubbleRowRight: { justifyContent: 'flex-end' },
  bubbleRowLeft: { justifyContent: 'flex-start' },
  bubble: {
    maxWidth: '76%',
    borderRadius: radius.xl,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: 4,
  },
  bubbleMerchant: {
    backgroundColor: colours.primary,
    borderBottomRightRadius: 4,
  },
  bubbleOther: {
    backgroundColor: colours.surfaceMuted,
    borderBottomLeftRadius: 4,
    borderWidth: 1,
    borderColor: colours.divider,
  },
  senderName: { fontSize: typography.xxs, lineHeight: Platform.select({ web: 16, default: 30 }), fontWeight: '700', color: colours.textSubtle },
  bubbleImage: { width: 200, height: 150, borderRadius: radius.lg },
  bubbleText: { fontSize: typography.sm, lineHeight: Platform.select({ web: 20, default: 42 }) },
  bubbleTextMerchant: { color: colours.backgroundDark },
  bubbleTextOther: { color: colours.textOnLight },
  bubbleFooter: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-end', gap: 3 },
  bubbleTime: { fontSize: typography.xxs, lineHeight: Platform.select({ web: 16, default: 30 }) },
  bubbleTimeMerchant: { color: 'rgba(15,26,20,0.55)' },
  bubbleTimeOther: { color: colours.textSubtle },

  sendErrorBanner: { paddingHorizontal: spacing.md, paddingVertical: spacing.xs, backgroundColor: colours.error + '12', borderTopWidth: 1, borderTopColor: colours.error + '33' },
  sendErrorText: { fontSize: typography.xxs, color: colours.error, textAlign: 'center' },

  inputBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colours.surfaceMuted,
    borderTopWidth: 1,
    borderTopColor: colours.divider,
  },
  attachBtn: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  textInput: {
    flex: 1,
    backgroundColor: colours.surface,
    borderRadius: radius.xl,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontSize: typography.sm,
    color: colours.textOnLight,
    maxHeight: 120,
    borderWidth: 1,
    borderColor: colours.divider,
  },
  sendBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colours.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendBtnDisabled: { opacity: 0.35 },
  // Image preview strip (above input bar)
  imagePreviewStrip: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xs,
    backgroundColor: colours.surfaceMuted,
    borderTopWidth: 1,
    borderTopColor: colours.divider,
  },
  imagePreviewItem: {
    position: 'relative',
    width: 64,
    height: 64,
  },
  imagePreviewThumb: {
    width: 64,
    height: 64,
    borderRadius: radius.md,
    backgroundColor: colours.divider,
  },
  imagePreviewRemove: {
    position: 'absolute',
    top: -6,
    right: -6,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colours.textOnLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatLockedBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginHorizontal: spacing.md,
    marginVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colours.error + '14',
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colours.error + '33',
  },
  chatLockedText: { flex: 1, fontSize: typography.xxs, color: colours.error },
  chatWarningBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginHorizontal: spacing.md,
    marginBottom: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colours.warning + '14',
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colours.warning + '33',
  },
  chatWarningText: { flex: 1, fontSize: typography.xxs, color: colours.warning },
  photoOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.96)', justifyContent: 'center', alignItems: 'center' },
  photoFull: { width: '100%', height: '80%' },
  photoCloseBtn: { position: 'absolute', top: 52, right: spacing.md, width: 38, height: 38, borderRadius: 19, backgroundColor: 'rgba(255,255,255,0.12)', alignItems: 'center', justifyContent: 'center' },

  // Notice banner (privacy + expiry warning)
  noticeBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginHorizontal: spacing.md,
    marginTop: spacing.sm,
    marginBottom: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colours.warning + '18',
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colours.warning + '40',
  },
  noticeText: {
    flex: 1,
    fontSize: typography.xxs,
    lineHeight: Platform.select({ web: 14, default: 18 }),
    color: colours.warning,
  },

  // Swipe-to-reply hint icons
  replyHintLeft: {
    position: 'absolute',
    left: 2,
    top: 0,
    bottom: 0,
    width: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  replyHintRight: {
    position: 'absolute',
    right: 2,
    top: 0,
    bottom: 0,
    width: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  // Web-only: push messages to bottom of flex area (inverted not supported on RN Web)
  listContentWeb: {
    flexGrow: 1,
    justifyContent: 'flex-end',
  },

  // Reply bar above input bar
  replyBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colours.surfaceMuted,
    borderTopWidth: 1,
    borderTopColor: colours.divider,
  },
  replyBarIndicator: {
    width: 3,
    alignSelf: 'stretch',
    borderRadius: 2,
    backgroundColor: colours.primary,
  },
  replyBarContent: { flex: 1, gap: 2 },
  replyBarSender: {
    fontSize: typography.xxs,
    lineHeight: Platform.select({ web: 14, default: 18 }),
    fontWeight: '700',
    color: colours.primary,
  },
  replyBarText: {
    fontSize: typography.xxs,
    lineHeight: Platform.select({ web: 14, default: 18 }),
    color: colours.textSubtle,
  },

  // Quoted reply inside a bubble
  replyQuote: {
    borderLeftWidth: 3,
    borderLeftColor: colours.primary + '88',
    paddingLeft: spacing.sm,
    paddingVertical: 2,
    marginBottom: 4,
    gap: 2,
  },
  replyQuoteSender: {
    fontSize: typography.xxs,
    lineHeight: Platform.select({ web: 14, default: 18 }),
    fontWeight: '700',
    color: colours.primary,
  },
  replyQuoteText: {
    fontSize: typography.xxs,
    lineHeight: Platform.select({ web: 14, default: 18 }),
    color: colours.textSubtle,
  },
});
