import { StyleSheet } from 'react-native';
import { colours } from '../../../shared/theme/colours';
import { spacing } from '../../../shared/theme/spacing';
import { typography } from '../../../shared/theme/typography';
import { radius } from '../../../shared/theme/radius';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colours.backgroundDark },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colours.backgroundDark },
  scroll: { flex: 1 },
  scrollContent: { padding: spacing.lg, gap: spacing.md, paddingBottom: spacing.xxl },

  // ── Page header ──────────────────────────────────────────────────────────────
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colours.dividerDark,
    marginBottom: spacing.md,
  },
  headerTitle: {
    fontSize: typography.display,
    fontWeight: '800',
    color: colours.textOnDark,
    letterSpacing: -0.8,
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs + 2,
    backgroundColor: colours.primary,
    borderRadius: radius.full,
  },
  editButtonText: { color: colours.backgroundDark, fontSize: typography.sm, fontWeight: '700' },

  // ── Cards ─────────────────────────────────────────────────────────────────────
  card: {
    backgroundColor: colours.backgroundMid,
    borderRadius: radius.xl,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colours.dividerDark,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 2,
    borderBottomWidth: 1,
    borderBottomColor: colours.dividerDark,
  },
  cardTitle: {
    fontSize: typography.xxs,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.45)',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  cardBody: { padding: spacing.md, gap: spacing.sm + 2 },
  divider: { height: 1, backgroundColor: colours.dividerDark },

  // ── Status ────────────────────────────────────────────────────────────────────
  statusWarningBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    backgroundColor: colours.warning + '18',
    borderBottomWidth: 1,
    borderBottomColor: colours.warning + '33',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  statusWarningText: { flex: 1, fontSize: typography.xs, color: colours.warning, fontWeight: '600' },
  statusRow: { flexDirection: 'row', gap: spacing.sm, flexWrap: 'wrap', padding: spacing.md },
  statusChip: {
    flex: 1,
    paddingVertical: spacing.sm + 4,
    borderRadius: radius.lg,
    borderWidth: 1.5,
    borderColor: colours.dividerDark,
    alignItems: 'center',
    backgroundColor: colours.backgroundDark,
  },
  statusChipActive: { borderColor: 'transparent' },
  statusChipText: { fontSize: typography.sm, fontWeight: '600', color: 'rgba(255,255,255,0.4)' },

  // ── Profile info rows ─────────────────────────────────────────────────────────
  infoRow: { flexDirection: 'row', gap: spacing.sm, alignItems: 'flex-start' },
  infoLabel: { width: 80, fontSize: typography.sm, color: 'rgba(255,255,255,0.4)', fontWeight: '500', flexShrink: 0 },
  infoValue: { flex: 1, fontSize: typography.sm, color: colours.textOnDark, fontWeight: '500' },

  // ── Form inputs ───────────────────────────────────────────────────────────────
  inputGroup: { gap: spacing.xs },
  inputLabel: { fontSize: typography.xxs, fontWeight: '700', color: 'rgba(255,255,255,0.4)', textTransform: 'uppercase', letterSpacing: 0.8 },
  input: {
    borderWidth: 1.5,
    borderColor: colours.dividerDark,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontSize: typography.sm,
    color: colours.textOnDark,
    backgroundColor: colours.backgroundDark,
    minHeight: 48,
  },
  inputFocused: { borderColor: colours.primary },
  inputMultiline: { minHeight: 80, textAlignVertical: 'top' },
  formBody: { padding: spacing.md, gap: spacing.md },
  formActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingVertical: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colours.dividerDark,
    marginTop: spacing.xs,
  },
  saveButton: {
    flex: 1,
    backgroundColor: colours.primary,
    borderRadius: radius.full,
    paddingVertical: spacing.xs + 4,
    alignItems: 'center',
  },
  saveButtonDisabled: { opacity: 0.5 },
  saveButtonText: { color: colours.backgroundDark, fontSize: typography.sm, fontWeight: '700' },
  cancelButton: {
    flex: 1,
    backgroundColor: colours.backgroundDark,
    borderRadius: radius.full,
    paddingVertical: spacing.xs + 4,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: colours.dividerDark,
  },
  cancelButtonText: { color: 'rgba(255,255,255,0.5)', fontSize: typography.sm, fontWeight: '600' },

  // ── Photo rows ────────────────────────────────────────────────────────────────
  photoRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingVertical: spacing.sm },
  photoPreview: { width: 60, height: 60, borderRadius: radius.md, backgroundColor: colours.backgroundDark },
  logoPreview: { width: 60, height: 60, borderRadius: radius.md, backgroundColor: colours.backgroundDark },
  photoInfo: { flex: 1, gap: 2 },
  photoLabel: { fontSize: typography.sm, fontWeight: '600', color: colours.textOnDark },
  photoDesc: { fontSize: typography.xs, color: 'rgba(255,255,255,0.35)', lineHeight: 18 },
  photoActions: { flexDirection: 'row', gap: spacing.sm },
  photoBtn: {
    paddingHorizontal: spacing.sm + 2,
    paddingVertical: spacing.xs + 2,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colours.dividerDark,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 34,
  },
  photoBtnDanger: { borderColor: colours.error + '55' },
  photoBtnText: { fontSize: typography.xs, fontWeight: '600', color: 'rgba(255,255,255,0.5)' },
  photoUploadBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    marginTop: spacing.xs,
    paddingVertical: spacing.sm,
    borderRadius: radius.lg,
    borderWidth: 1.5,
    borderColor: colours.dividerDark,
    borderStyle: 'dashed',
    backgroundColor: colours.backgroundDark,
  },

  // ── Delivery / hours / toggles ────────────────────────────────────────────────
  toggleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  toggleLabel: { fontSize: typography.sm, color: colours.textOnDark, fontWeight: '500' },
  hoursHeader: { flexDirection: 'row', paddingHorizontal: spacing.md, paddingTop: spacing.sm, paddingBottom: spacing.xs, borderBottomWidth: 1, borderBottomColor: colours.dividerDark },
  hoursRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing.md, paddingVertical: spacing.xs + 2, borderBottomWidth: 1, borderBottomColor: colours.dividerDark },
  hoursReadRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  hoursCell: { fontSize: typography.xs, color: 'rgba(255,255,255,0.4)', fontWeight: '600' as const },
  hoursDayCell: { width: 36 },
  hoursTimeCell: { flex: 1, marginHorizontal: 4 },
  hoursStatusCell: { width: 48 },
  hoursInput: { borderWidth: 1, borderColor: colours.dividerDark, borderRadius: radius.sm, paddingHorizontal: 6, paddingVertical: 4, fontSize: typography.xs, color: colours.textOnDark, backgroundColor: colours.backgroundDark, fontWeight: '400' },
  hoursInputDisabled: { opacity: 0.3 },
  hoursDayLabel: { width: 36, fontSize: typography.sm, color: colours.textOnDark, fontWeight: '700' },
  hoursClosed: { fontSize: typography.sm, color: 'rgba(255,255,255,0.3)', fontStyle: 'italic' },
  hoursTime: { fontSize: typography.sm, color: colours.textOnDark, fontWeight: '500' },
  editDeliveryBtn: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  editDeliveryBtnText: { fontSize: typography.xs, fontWeight: '700', color: colours.primary, textTransform: 'uppercase', letterSpacing: 0.5 },
  deliveryEditRow: { gap: spacing.xs },
  deliveryEditInputWrap: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  deliveryEditCurrency: { fontSize: typography.sm, fontWeight: '600', color: 'rgba(255,255,255,0.4)' },
  deliveryEditInput: { flex: 1, borderWidth: 1.5, borderColor: colours.primary, borderRadius: radius.lg, paddingHorizontal: spacing.md, paddingVertical: spacing.xs + 2, fontSize: typography.sm, color: colours.textOnDark, backgroundColor: colours.backgroundDark, minHeight: 44 },
  deliveryEditActions: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.xs },
  deliveryEditCancel: { flex: 1, paddingVertical: spacing.xs + 2, borderRadius: radius.full, borderWidth: 1.5, borderColor: colours.dividerDark, alignItems: 'center' },
  deliveryEditCancelText: { fontSize: typography.sm, color: 'rgba(255,255,255,0.4)', fontWeight: '600' },
  deliveryEditSave: { flex: 1, paddingVertical: spacing.xs + 2, borderRadius: radius.full, backgroundColor: colours.primary, alignItems: 'center' },
  deliveryEditSaveText: { fontSize: typography.sm, color: colours.backgroundDark, fontWeight: '700' },

  // ── Support / KYC ─────────────────────────────────────────────────────────────
  supportButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs + 2,
    paddingVertical: spacing.md,
    borderRadius: radius.full,
    borderWidth: 1.5,
    borderColor: colours.primary,
    backgroundColor: colours.primary + '18',
  },
  supportButtonText: { fontSize: typography.sm, fontWeight: '700', color: colours.primary },
  kycNote: { flexDirection: 'row', flexWrap: 'wrap', paddingHorizontal: spacing.md, paddingBottom: spacing.sm, alignItems: 'center' },
  kycNoteText: { fontSize: typography.xxs, color: 'rgba(255,255,255,0.3)', fontStyle: 'italic' },
  kycNoteLink: { fontSize: typography.xxs, color: colours.primary, fontWeight: '700' },
  infoRowWithAction: { flexDirection: 'row', alignItems: 'center' },
  inlineEditBtn: { padding: 6, marginLeft: spacing.xs },

  // ── Modal (bottom sheet dark) ─────────────────────────────────────────────────
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.65)', justifyContent: 'flex-end' },
  modalSheet: {
    backgroundColor: colours.backgroundMid,
    borderTopLeftRadius: radius.sheet,
    borderTopRightRadius: radius.sheet,
    maxHeight: '90%',
    borderWidth: 1,
    borderColor: colours.dividerDark,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colours.dividerDark,
  },
  modalTitle: { fontSize: typography.lg, fontWeight: '800', color: colours.textOnDark, letterSpacing: -0.4 },
  modalBody: { padding: spacing.lg, gap: spacing.md },
  modalNote: { fontSize: typography.sm, color: 'rgba(255,255,255,0.4)', lineHeight: 20 },
  modalDocNote: { fontSize: typography.sm, color: 'rgba(255,255,255,0.4)', lineHeight: 20, backgroundColor: colours.backgroundDark, padding: spacing.sm, borderRadius: radius.lg },
});
