import { StyleSheet } from 'react-native';
import { colours } from '../../../shared/theme/colours';
import { spacing } from '../../../shared/theme/spacing';
import { typography } from '../../../shared/theme/typography';
import { radius } from '../../../shared/theme/radius';

const floatingCard = {
  backgroundColor: colours.surface,
  borderRadius: radius.xl,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.06,
  shadowRadius: 10,
  elevation: 3,
};

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colours.backgroundDark,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    padding: spacing.md,
    paddingBottom: spacing.xxl,
    gap: spacing.md,
    width: '100%',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xl + spacing.md,
    backgroundColor: colours.backgroundDark,
    marginTop: -spacing.md,
    marginHorizontal: -spacing.md,
  },
  headerTitle: {
    fontSize: typography.display,
    fontWeight: '800',
    color: colours.textOnDark,
    letterSpacing: -0.8,
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs + 2,
    backgroundColor: colours.primary,
    borderRadius: radius.full,
    shadowColor: colours.primary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  editButtonText: {
    color: colours.white,
    fontSize: typography.sm,
    fontWeight: '700',
  },
  card: {
    ...floatingCard,
    overflow: 'hidden',
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 2,
    backgroundColor: colours.backgroundDark,
    borderBottomWidth: 0,
  },
  cardTitle: {
    fontSize: typography.xxs,
    fontWeight: '800',
    color: 'rgba(255,255,255,0.5)',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  cardBody: {
    padding: spacing.md,
    gap: spacing.sm,
  },
  divider: {
    height: 1,
    backgroundColor: colours.divider,
    marginVertical: 2,
  },
  infoRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    alignItems: 'flex-start',
  },
  infoLabel: {
    width: 90,
    fontSize: typography.sm,
    color: colours.textMuted,
    fontWeight: '500',
    flexShrink: 0,
  },
  infoValue: {
    flex: 1,
    fontSize: typography.sm,
    color: colours.textOnLight,
    fontWeight: '500',
  },
  statusWarningBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    backgroundColor: colours.warningBg,
    borderBottomWidth: 1,
    borderBottomColor: colours.warning + '33',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  statusWarningText: {
    flex: 1,
    fontSize: typography.xs,
    color: colours.warning,
    fontWeight: '600',
  },
  statusRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    flexWrap: 'wrap',
    padding: spacing.md,
  },
  statusChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs + 2,
    borderRadius: radius.full,
    borderWidth: 1.5,
    borderColor: colours.divider,
    backgroundColor: colours.surfaceMuted,
  },
  statusChipActive: {
    borderColor: 'transparent',
  },
  statusChipText: {
    fontSize: typography.sm,
    fontWeight: '600',
    color: colours.textMuted,
  },
  inputGroup: {
    gap: spacing.xs,
  },
  inputLabel: {
    fontSize: typography.xxs,
    fontWeight: '700',
    color: colours.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  input: {
    borderWidth: 1.5,
    borderColor: colours.divider,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontSize: typography.sm,
    color: colours.textOnLight,
    backgroundColor: colours.surfaceMuted,
    minHeight: 48,
  },
  inputFocused: {
    borderColor: colours.primary,
    backgroundColor: colours.surface,
  },
  inputMultiline: {
    minHeight: 80,
    textAlignVertical: 'top',
  },
  formBody: {
    padding: spacing.md,
    gap: spacing.md,
  },
  formActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colours.divider,
  },
  saveButton: {
    flex: 1,
    backgroundColor: colours.primary,
    borderRadius: radius.full,
    paddingVertical: spacing.sm + 2,
    alignItems: 'center',
    shadowColor: colours.primary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  saveButtonDisabled: {
    opacity: 0.5,
    shadowOpacity: 0,
    elevation: 0,
  },
  saveButtonText: {
    color: colours.white,
    fontSize: typography.sm,
    fontWeight: '700',
  },
  cancelButton: {
    flex: 1,
    backgroundColor: colours.surface,
    borderRadius: radius.full,
    paddingVertical: spacing.sm + 2,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: colours.divider,
  },
  cancelButtonText: {
    color: colours.textMuted,
    fontSize: typography.sm,
    fontWeight: '600',
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colours.backgroundLight,
    gap: spacing.sm,
  },
  editDeliveryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  editDeliveryBtnText: {
    fontSize: typography.xs,
    fontWeight: '700',
    color: colours.primary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  deliveryEditRow: {
    gap: spacing.xs,
  },
  deliveryEditInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  deliveryEditCurrency: {
    fontSize: typography.sm,
    fontWeight: '600',
    color: colours.textMuted,
  },
  deliveryEditInput: {
    flex: 1,
    borderWidth: 1.5,
    borderColor: colours.primary,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs + 2,
    fontSize: typography.sm,
    color: colours.textOnLight,
    backgroundColor: colours.surfaceMuted,
    minHeight: 44,
  },
  deliveryEditActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  deliveryEditCancel: {
    flex: 1,
    paddingVertical: spacing.xs + 2,
    borderRadius: radius.full,
    borderWidth: 1.5,
    borderColor: colours.divider,
    alignItems: 'center',
  },
  deliveryEditCancelText: {
    fontSize: typography.sm,
    color: colours.textMuted,
    fontWeight: '600',
  },
  deliveryEditSave: {
    flex: 1,
    paddingVertical: spacing.xs + 2,
    borderRadius: radius.full,
    backgroundColor: colours.primary,
    alignItems: 'center',
  },
  deliveryEditSaveText: {
    fontSize: typography.sm,
    color: colours.white,
    fontWeight: '700',
  },
  photoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    marginTop: spacing.xs,
  },
  photoPreview: {
    width: 110,
    height: 70,
    borderRadius: radius.lg,
    backgroundColor: colours.surfaceMuted,
  },
  logoPreview: {
    width: 70,
    height: 70,
    borderRadius: radius.xl,
    backgroundColor: colours.surfaceMuted,
  },
  photoActions: {
    flex: 1,
    flexDirection: 'row',
    gap: spacing.sm,
  },
  photoBtn: {
    flex: 1,
    paddingVertical: spacing.xs + 2,
    borderRadius: radius.full,
    borderWidth: 1.5,
    borderColor: colours.divider,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 38,
  },
  photoBtnDanger: {
    borderColor: colours.error + '55',
  },
  photoBtnText: {
    fontSize: typography.xs,
    fontWeight: '600',
    color: colours.textMuted,
  },
  photoUploadBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    marginTop: spacing.xs,
    paddingVertical: spacing.sm,
    borderRadius: radius.lg,
    borderWidth: 1.5,
    borderColor: colours.primary,
    borderStyle: 'dashed',
    backgroundColor: colours.primaryGlow,
  },
  supportButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs + 2,
    paddingVertical: spacing.md,
    borderRadius: radius.full,
    borderWidth: 1.5,
    borderColor: colours.primary,
    backgroundColor: colours.primaryGlow,
  },
  supportButtonText: {
    fontSize: typography.sm,
    fontWeight: '700',
    color: colours.primary,
  },
  kycNote: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.sm,
    alignItems: 'center',
  },
  kycNoteText: {
    fontSize: typography.xxs,
    color: colours.textMuted,
    fontStyle: 'italic',
  },
  kycNoteLink: {
    fontSize: typography.xxs,
    color: colours.primary,
    fontWeight: '700',
  },
  infoRowWithAction: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  inlineEditBtn: {
    padding: 6,
    marginLeft: spacing.xs,
  },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  toggleLabel: {
    fontSize: typography.sm,
    color: colours.textOnLight,
    fontWeight: '600',
  },
  // Opening hours
  hoursHeader: {
    flexDirection: 'row',
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xs,
    borderBottomWidth: 1,
    borderBottomColor: colours.divider,
  },
  hoursRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs + 2,
    borderBottomWidth: 1,
    borderBottomColor: colours.divider,
  },
  hoursReadRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  hoursCell: {
    fontSize: typography.xs,
    color: colours.textMuted,
    fontWeight: '700' as const,
  },
  hoursDayCell: {
    width: 36,
  },
  hoursTimeCell: {
    flex: 1,
    marginHorizontal: 4,
  },
  hoursStatusCell: {
    width: 48,
  },
  hoursInput: {
    borderWidth: 1.5,
    borderColor: colours.divider,
    borderRadius: radius.md,
    paddingHorizontal: 6,
    paddingVertical: 4,
    fontSize: typography.xs,
    color: colours.textOnLight,
    backgroundColor: colours.surfaceMuted,
    fontWeight: '400',
  },
  hoursInputDisabled: {
    opacity: 0.3,
  },
  hoursDayLabel: {
    width: 36,
    fontSize: typography.sm,
    color: colours.textOnLight,
    fontWeight: '700',
  },
  hoursClosed: {
    fontSize: typography.sm,
    color: colours.textMuted,
    fontStyle: 'italic',
  },
  hoursTime: {
    fontSize: typography.sm,
    color: colours.textOnLight,
    fontWeight: '500',
  },
  // Modal (bottom sheet)
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: colours.backgroundDark,
    borderTopLeftRadius: radius.sheet,
    borderTopRightRadius: radius.sheet,
    maxHeight: '90%',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colours.dividerDark,
  },
  modalTitle: {
    fontSize: typography.lg,
    fontWeight: '800',
    color: colours.textOnDark,
    letterSpacing: -0.4,
  },
  modalBody: {
    padding: spacing.lg,
    gap: spacing.md,
  },
  modalNote: {
    fontSize: typography.sm,
    color: 'rgba(255,255,255,0.45)',
    lineHeight: 20,
  },
  modalDocNote: {
    fontSize: typography.sm,
    color: 'rgba(255,255,255,0.45)',
    lineHeight: 20,
    backgroundColor: colours.dividerDark,
    padding: spacing.sm,
    borderRadius: radius.lg,
  },
});
