import { StyleSheet } from 'react-native';
import { colours } from '../../../shared/theme/colours';
import { radius } from '../../../shared/theme/radius';
import { spacing } from '../../../shared/theme/spacing';
import { typography } from '../../../shared/theme/typography';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colours.backgroundDark },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 2,
    backgroundColor: colours.backgroundDark,
    gap: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colours.dividerDark,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: radius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colours.backgroundMid,
    borderWidth: 1,
    borderColor: colours.dividerDark,
  },
  headerInfo: { flex: 1 },
  topBarTitle: { fontSize: typography.md, fontWeight: '700', color: colours.textOnDark },
  topBarSub: { fontSize: typography.xxs, color: 'rgba(255,255,255,0.35)', marginTop: 1 },
  body: { flex: 1, backgroundColor: colours.backgroundDark },
  list: { flex: 1 },
  listContent: { paddingHorizontal: spacing.md, paddingVertical: spacing.md, gap: spacing.sm },
  emptyWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: spacing.xxl },
  emptyText: { fontSize: typography.sm, color: 'rgba(255,255,255,0.3)', textAlign: 'center', marginTop: 8 },
  loaderWrap: { flex: 1, alignItems: 'center', justifyContent: 'center' },

  bubbleRow: { flexDirection: 'row' },
  bubbleRowRight: { justifyContent: 'flex-end' },
  bubbleRowLeft: { justifyContent: 'flex-start' },
  bubble: {
    maxWidth: '76%',
    borderRadius: radius.xl,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: 4,
  },
  bubbleMerchant: {
    backgroundColor: colours.primary,
    borderBottomRightRadius: 4,
  },
  bubbleOther: {
    backgroundColor: colours.backgroundMid,
    borderBottomLeftRadius: 4,
    borderWidth: 1,
    borderColor: colours.dividerDark,
  },
  senderName: { fontSize: typography.xxs, fontWeight: '700', color: 'rgba(255,255,255,0.4)' },
  bubbleImage: { width: 200, height: 150, borderRadius: radius.lg },
  bubbleText: { fontSize: typography.sm, lineHeight: 20 },
  bubbleTextMerchant: { color: colours.backgroundDark },
  bubbleTextOther: { color: colours.textOnDark },
  bubbleTime: { fontSize: typography.xxs, alignSelf: 'flex-end' },
  bubbleTimeMerchant: { color: 'rgba(15,26,20,0.55)' },
  bubbleTimeOther: { color: 'rgba(255,255,255,0.3)' },

  sendErrorBanner: { paddingHorizontal: spacing.md, paddingVertical: spacing.xs, backgroundColor: colours.error + '18', borderTopWidth: 1, borderTopColor: colours.error + '33' },
  sendErrorText: { fontSize: typography.xxs, color: colours.error, textAlign: 'center' },

  inputBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colours.backgroundMid,
    borderTopWidth: 1,
    borderTopColor: colours.dividerDark,
  },
  attachBtn: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  textInput: {
    flex: 1,
    backgroundColor: colours.backgroundDark,
    borderRadius: radius.xl,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontSize: typography.sm,
    color: colours.textOnDark,
    maxHeight: 100,
    borderWidth: 1,
    borderColor: colours.dividerDark,
  },
  sendBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colours.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendBtnDisabled: { opacity: 0.35 },
  photoOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.96)', justifyContent: 'center', alignItems: 'center' },
  photoFull: { width: '100%', height: '80%' },
  photoCloseBtn: { position: 'absolute', top: 52, right: spacing.md, width: 38, height: 38, borderRadius: 19, backgroundColor: 'rgba(255,255,255,0.12)', alignItems: 'center', justifyContent: 'center' },
});
