import { StyleSheet } from 'react-native';
import { colours } from '@/shared/theme/colours';
import { radius } from '@/shared/theme/radius';
import { spacing } from '@/shared/theme/spacing';
import { typography } from '@/shared/theme/typography';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colours.backgroundDark },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    backgroundColor: colours.backgroundDark,
    gap: spacing.sm,
  },
  headerTitle: {
    fontSize: typography.lg,
    fontWeight: '800',
    color: colours.textOnDark,
    flex: 1,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  keyboardAvoid: { flex: 1 },
  scroll: { flex: 1, backgroundColor: colours.backgroundLight },
  content: { padding: spacing.md, gap: spacing.md },
  card: {
    backgroundColor: colours.card,
    borderRadius: radius.xl,
    overflow: 'hidden',
    paddingVertical: spacing.xs,
  },
  sectionTitle: {
    fontSize: typography.xxs,
    fontWeight: '700',
    color: colours.textMuted,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginBottom: spacing.xs,
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colours.divider,
  },
  itemInfo: {
    flex: 1,
  },
  itemName: {
    fontSize: typography.sm,
    color: colours.textOnLight,
    fontWeight: '500',
  },
  itemOptions: {
    fontSize: typography.xxs,
    color: colours.textMuted,
    marginTop: 2,
    lineHeight: 14,
  },
  itemQty: {
    fontSize: typography.sm,
    color: colours.medium,
    marginRight: spacing.sm,
  },
  itemPrice: {
    fontSize: typography.sm,
    fontWeight: '700',
    color: colours.textOnLight,
    minWidth: 56,
    textAlign: 'right',
  },
  qtyControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginRight: spacing.sm,
  },
  qtyBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colours.backgroundLight,
    borderWidth: 1,
    borderColor: colours.divider,
    alignItems: 'center',
    justifyContent: 'center',
  },
  qtyBtnText: {
    fontSize: 16,
    lineHeight: 20,
    color: colours.textMuted,
    fontWeight: '600',
  },
  qtyBtnActive: {
    borderColor: colours.primary,
  },
  qtyBtnTextActive: {
    color: colours.primary,
  },
  qtyValue: {
    fontSize: typography.sm,
    fontWeight: '700',
    color: colours.textOnLight,
    minWidth: 18,
    textAlign: 'center',
  },
  totalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
  },
  totalLabel: {
    fontSize: typography.md,
    fontWeight: '700',
    color: colours.textOnLight,
  },
  totalValue: {
    fontSize: typography.md,
    fontWeight: '800',
    color: colours.primary,
  },
  paymentOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colours.divider,
    gap: spacing.sm,
  },
  paymentLabel: {
    flex: 1,
    fontSize: typography.md,
    color: colours.textOnLight,
    fontWeight: '500',
  },
  radioOuter: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: colours.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colours.primary,
  },
  notesInput: {
    backgroundColor: colours.card,
    borderRadius: radius.xl,
    padding: spacing.md,
    fontSize: typography.sm,
    color: colours.textOnLight,
    minHeight: 80,
    textAlignVertical: 'top',
  },
  placeBtn: {
    backgroundColor: colours.primary,
    borderRadius: radius.xl,
    paddingVertical: spacing.md,
    alignItems: 'center',
    marginTop: spacing.sm,
    marginBottom: spacing.xl,
  },
  placeBtnLine: {
    backgroundColor: '#00B900',
  },
  placeBtnDisabled: { opacity: 0.5 },
  placeBtnRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  placeBtnText: {
    fontSize: typography.md,
    fontWeight: '700',
    color: colours.white,
    letterSpacing: 0.3,
  },

  // ── Delivery address section ───────────────────────────────────────────────
  addressEmpty: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: colours.card,
    borderRadius: radius.xl,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderWidth: 1.5,
    borderColor: colours.divider,
    borderStyle: 'dashed',
  },
  addressEmptyText: {
    flex: 1,
    fontSize: typography.sm,
    color: colours.textMuted,
    fontWeight: '500',
  },
  addressCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: colours.card,
    borderRadius: radius.xl,
    padding: spacing.md,
    borderWidth: 1.5,
    borderColor: colours.primary,
  },
  addressIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: colours.infoBg,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.sm,
    marginTop: 2,
  },
  addressBody: {
    flex: 1,
    gap: 3,
  },
  addressTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  addressLabelChip: {
    backgroundColor: colours.infoBg,
    borderRadius: radius.sm,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  addressLabelText: {
    fontSize: typography.xxs,
    fontWeight: '700',
    color: colours.primary,
    letterSpacing: 1,
  },
  addressText: {
    fontSize: typography.sm,
    fontWeight: '500',
    color: colours.textOnLight,
    lineHeight: 18,
  },
  addressSecondary: {
    fontSize: typography.xs,
    color: colours.textMuted,
    lineHeight: 16,
  },
  changeBtn: {
    fontSize: typography.sm,
    fontWeight: '700',
    color: colours.primary,
    marginLeft: spacing.sm,
    marginTop: 4,
  },
});
