import { StyleSheet } from 'react-native';
import { colours } from '@/shared/theme/colours';
import { radius } from '@/shared/theme/radius';
import { spacing } from '@/shared/theme/spacing';
import { typography } from '@/shared/theme/typography';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colours.backgroundDark },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    backgroundColor: colours.backgroundDark,
    gap: spacing.sm,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: radius.full,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    fontSize: typography.lg,
    fontWeight: '800',
    color: colours.textOnDark,
    lineHeight: 50,
  },
  scroll: { flex: 1, backgroundColor: colours.backgroundLight },
  photo: { width: '100%', height: 240, backgroundColor: colours.infoBg },
  infoBlock: {
    backgroundColor: colours.card,
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colours.divider,
  },
  itemName: {
    fontSize: typography.xl,
    fontWeight: '800',
    color: colours.textOnLight,
    letterSpacing: -0.3,
    lineHeight: 60,
    marginBottom: spacing.xs,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.xs,
  },
  originalPrice: {
    fontSize: typography.sm,
    color: colours.textMuted,
    textDecorationLine: 'line-through',
  },
  price: {
    fontSize: typography.lg,
    fontWeight: '700',
    color: colours.primary,
  },
  description: {
    fontSize: typography.sm,
    color: colours.medium,
    lineHeight: 20,
    marginTop: spacing.xs,
  },
  groupBlock: {
    backgroundColor: colours.card,
    marginTop: spacing.sm,
    paddingVertical: spacing.sm,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: colours.divider,
  },
  groupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.xs,
  },
  groupName: {
    fontSize: typography.sm,
    fontWeight: '700',
    color: colours.textOnLight,
    flex: 1,
  },
  groupMeta: {
    fontSize: typography.xxs,
    fontWeight: '600',
    letterSpacing: 0.3,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: radius.full,
    overflow: 'hidden',
  },
  groupMetaRequired: {
    backgroundColor: colours.primary + '18',
    color: colours.primary,
  },
  groupMetaOptional: {
    backgroundColor: colours.infoBg,
    color: colours.textMuted,
  },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colours.divider,
  },
  optionLabel: {
    flex: 1,
    fontSize: typography.sm,
    color: colours.textOnLight,
  },
  optionPrice: {
    fontSize: typography.sm,
    color: colours.textMuted,
  },
  selector: {
    width: 22,
    height: 22,
    borderRadius: radius.full,
    borderWidth: 2,
    borderColor: colours.divider,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectorSquare: {
    borderRadius: radius.sm,
  },
  selectorActive: {
    borderColor: colours.primary,
    backgroundColor: colours.primary,
  },
  selectorDot: {
    width: 10,
    height: 10,
    borderRadius: radius.full,
    backgroundColor: colours.white,
  },
  noteBlock: {
    backgroundColor: colours.card,
    marginTop: spacing.sm,
    padding: spacing.md,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: colours.divider,
  },
  noteLabel: {
    fontSize: typography.sm,
    fontWeight: '600',
    color: colours.textMuted,
    marginBottom: spacing.xs,
  },
  noteInput: {
    fontSize: typography.sm,
    color: colours.textOnLight,
    borderWidth: 1,
    borderColor: colours.divider,
    borderRadius: radius.md,
    padding: spacing.sm,
    minHeight: 60,
    textAlignVertical: 'top',
  },
  bottomBar: {
    backgroundColor: colours.card,
    borderTopWidth: 1,
    borderTopColor: colours.divider,
    padding: spacing.md,
    gap: spacing.sm,
  },
  quantityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.lg,
  },
  qtyBtn: {
    width: 40,
    height: 40,
    borderRadius: radius.full,
    backgroundColor: colours.infoBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  qtyBtnActive: {
    backgroundColor: colours.primary,
  },
  qtyBtnText: {
    fontSize: typography.xl,
    fontWeight: '700',
    color: colours.primary,
    lineHeight: 28,
  },
  qtyBtnTextActive: {
    color: colours.white,
  },
  qtyValue: {
    fontSize: typography.lg,
    fontWeight: '700',
    color: colours.textOnLight,
    minWidth: 32,
    textAlign: 'center',
  },
  addBtn: {
    backgroundColor: colours.primary,
    borderRadius: radius.xl,
    paddingVertical: spacing.md,
    alignItems: 'center',
  },
  addBtnDisabled: {
    backgroundColor: colours.textMuted,
    opacity: 0.5,
  },
  addBtnText: {
    fontSize: typography.md,
    fontWeight: '700',
    color: colours.white,
    letterSpacing: 0.3,
  },
  spacer: { height: 120 },
});
