import { Platform, StyleSheet } from 'react-native';
import { colours } from '@/shared/theme/colours';
import { radius } from '@/shared/theme/radius';
import { spacing } from '@/shared/theme/spacing';
import { typography } from '@/shared/theme/typography';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colours.backgroundDark },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colours.backgroundDark,
    gap: spacing.sm,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerInfo: { flex: 1 },
  headerTitle: {
    fontSize: typography.md,
    fontWeight: '800',
    color: colours.textOnDark,
  },
  headerSub: {
    fontSize: typography.xxs,
    color: 'rgba(255,255,255,0.55)',
    marginTop: 1,
  },
  body: { flex: 1, backgroundColor: colours.backgroundLight },
  noticeBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginHorizontal: spacing.md,
    marginTop: spacing.sm,
    marginBottom: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colours.warning + '18',
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colours.warning + '40',
  },
  noticeText: {
    flex: 1,
    fontSize: typography.xxs,
    lineHeight: Platform.select({ web: 14, default: 18 }),
    color: colours.warning,
  },
  list: { flex: 1, backgroundColor: colours.backgroundLight },
  listContent: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    gap: spacing.xs,
  },
  emptyWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: spacing.xxl },
  emptyText: { fontSize: typography.sm, color: colours.textMuted, textAlign: 'center' },
  loaderWrap: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  // Bubbles
  bubbleRow: { flexDirection: 'row' },
  bubbleRowRight: { justifyContent: 'flex-end' },
  bubbleRowLeft: { justifyContent: 'flex-start' },
  bubble: {
    maxWidth: '78%',
    borderRadius: radius.xl,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: 4,
  },
  bubbleCustomer: {
    backgroundColor: colours.primary,
    borderBottomRightRadius: 4,
  },
  bubbleOther: {
    backgroundColor: colours.card,
    borderBottomLeftRadius: 4,
    borderWidth: 1,
    borderColor: colours.divider,
  },
  senderName: {
    fontSize: typography.xxs,
    fontWeight: '700',
    color: colours.textMuted,
  },
  bubbleImage: { width: 180, height: 140, borderRadius: radius.lg },
  bubbleText: { fontSize: typography.sm, lineHeight: 40 },
  bubbleTextCustomer: { color: colours.white },
  bubbleTextOther: { color: colours.textOnLight },
  bubbleLinkCustomer: { color: colours.white, textDecorationLine: 'underline' } as const,
  bubbleLinkOther: { color: colours.primary, textDecorationLine: 'underline' } as const,
  bubbleFooter: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-end', gap: 3 },
  bubbleTime: { fontSize: typography.xxs },
  bubbleTimeCustomer: { color: 'rgba(255,255,255,0.6)' },
  bubbleTimeOther: { color: colours.textMuted },
  // Date separator
  dateSep: { alignItems: 'center', marginVertical: spacing.sm },
  dateSepText: {
    fontSize: typography.xxs,
    color: colours.textMuted,
    backgroundColor: colours.backgroundLight,
    paddingHorizontal: spacing.sm,
  },
  // Send error
  sendErrorBanner: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    backgroundColor: '#fee2e2',
    borderTopWidth: 1,
    borderTopColor: '#fca5a5',
  },
  sendErrorText: {
    fontSize: typography.xs,
    color: '#dc2626',
    textAlign: 'center',
  },
  // Input bar
  inputBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    backgroundColor: colours.card,
    borderTopWidth: 1,
    borderTopColor: colours.divider,
  },
  attachBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textInput: {
    flex: 1,
    backgroundColor: colours.backgroundLight,
    borderRadius: radius.xl,
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
    fontSize: typography.sm,
    color: colours.textOnLight,
    maxHeight: 100,
    borderWidth: 1,
    borderColor: colours.divider,
  },
  sendBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colours.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendBtnDisabled: { opacity: 0.4 },
  // Image preview strip (above input bar) — height on View, not ScrollView (iOS ignores it on ScrollView)
  imagePreviewStrip: {
    height: 82,
    backgroundColor: colours.card,
    borderTopWidth: 1,
    borderTopColor: colours.divider,
    overflow: 'hidden',
  },
  imagePreviewStripContent: {
    paddingHorizontal: spacing.md,
    paddingTop: 10,
    paddingBottom: spacing.xs,
    gap: spacing.xs,
    alignItems: 'flex-start',
  },
  imagePreviewItem: {
    position: 'relative',
    width: 64,
    height: 64,
  },
  imagePreviewThumb: {
    width: 64,
    height: 64,
    borderRadius: radius.md,
    backgroundColor: colours.divider,
  },
  imagePreviewRemove: {
    position: 'absolute',
    top: -6,
    right: -6,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colours.textOnLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // System notice bubble
  systemNotice: { alignItems: 'center', paddingVertical: spacing.xs },
  systemNoticeText: {
    fontSize: typography.xxs,
    fontStyle: 'italic',
    color: colours.textMuted,
    textAlign: 'center',
  },
  // Swipe-to-reply hints (bidirectional)
  replyHintLeft: {
    position: 'absolute',
    left: 2,
    top: 0,
    bottom: 0,
    width: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  replyHintRight: {
    position: 'absolute',
    right: 2,
    top: 0,
    bottom: 0,
    width: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  // Reply bar above input
  replyBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colours.card,
    borderTopWidth: 1,
    borderTopColor: colours.divider,
  },
  replyBarIndicator: {
    width: 3,
    alignSelf: 'stretch',
    borderRadius: 2,
    backgroundColor: colours.primary,
  },
  replyBarContent: { flex: 1, gap: 2 },
  replyBarSender: {
    fontSize: typography.xxs,
    lineHeight: Platform.select({ web: 14, default: 18 }),
    fontWeight: '700',
    color: colours.primary,
  },
  replyBarText: {
    fontSize: typography.xxs,
    lineHeight: Platform.select({ web: 14, default: 18 }),
    color: colours.textMuted,
  },
  // Quoted reply inside bubble — default for received (light) bubbles
  replyQuote: {
    borderLeftWidth: 3,
    borderLeftColor: colours.primary,
    borderRadius: 4,
    paddingLeft: spacing.sm,
    paddingRight: spacing.xs,
    paddingVertical: spacing.xs,
    marginBottom: 6,
    gap: 2,
    backgroundColor: colours.primary + '22',
  },
  // Customer's own bubble has a primary-coloured background — dark overlay so
  // the quote block reads as a clearly distinct darker patch.
  replyQuoteCustomer: {
    borderLeftColor: 'rgba(255,255,255,0.60)',
    backgroundColor: 'rgba(0,0,0,0.20)',
  },
  replyQuoteSender: {
    fontSize: typography.xxs,
    lineHeight: Platform.select({ web: 15, default: 20 }),
    fontWeight: '700',
    color: colours.primary,
  },
  replyQuoteSenderCustomer: { color: '#ffffff' },
  replyQuoteText: {
    fontSize: typography.xxs,
    lineHeight: Platform.select({ web: 14, default: 18 }),
    color: colours.textOnLight,
  },
  replyQuoteTextCustomer: { color: 'rgba(255,255,255,0.80)' },
  // Photo lightbox
  photoOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.92)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  photoFull: {
    width: '100%',
    height: '80%',
  },
  photoCloseBtn: {
    position: 'absolute',
    top: 52,
    right: spacing.md,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
