import { StyleSheet } from 'react-native';
import { colours } from '../../../shared/theme/colours';
import { spacing } from '../../../shared/theme/spacing';
import { typography } from '../../../shared/theme/typography';
import { radius } from '../../../shared/theme/radius';

export const styles = StyleSheet.create({
  // ── Mobile layout ─────────────────────────────────────────────────────────────
  safe: { flex: 1, backgroundColor: colours.backgroundDark },
  brandArea: {
    backgroundColor: colours.backgroundDark,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xl,
    gap: spacing.lg,
  },
  brandAreaContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    paddingTop: spacing.sm,
  },
  sheetScroll: {
    backgroundColor: '#f2f4f3',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    flex: 1,
  },
  sheetContent: {
    padding: spacing.lg,
    paddingTop: spacing.xl,
    paddingBottom: spacing.xxl,
    flexGrow: 1,
  },
  sheetTitle: {
    fontSize: 30,
    fontWeight: '900',
    color: colours.textOnLight,
    letterSpacing: -1,
    marginBottom: spacing.xs,
  },
  sheetSubtitle: {
    fontSize: typography.sm,
    color: colours.textMuted,
    marginBottom: spacing.xl,
  },

  // ── Web layout ────────────────────────────────────────────────────────────────
  screen: { flex: 1, flexDirection: 'row' },
  leftPanel: {
    width: '42%',
    backgroundColor: colours.backgroundDark,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xxl,
    gap: spacing.md,
  },
  rightPanel: { flex: 1, backgroundColor: '#f2f4f3', alignItems: 'center', justifyContent: 'center' },
  webScroll: { flex: 1, width: '100%' },
  webForm: { flexGrow: 1, justifyContent: 'center', maxWidth: 440, width: '100%', alignSelf: 'center', padding: spacing.xxl },
  formTitle: { fontSize: 30, fontWeight: '900', color: colours.textOnLight, marginBottom: spacing.xs, letterSpacing: -1 },
  formSubtitle: { fontSize: typography.sm, color: colours.textMuted, marginBottom: spacing.xl },

  // ── Brand ─────────────────────────────────────────────────────────────────────
  brandMark: {
    width: 52,
    height: 52,
    borderRadius: 14,
    backgroundColor: colours.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colours.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.45,
    shadowRadius: 20,
    elevation: 10,
  },
  brandMarkText: { fontSize: typography.xl, fontWeight: '900', color: colours.white },
  brandName: { fontSize: typography.xl, fontWeight: '900', color: colours.textOnDark, letterSpacing: -0.5 },
  brandRole: { fontSize: typography.xxs, fontWeight: '700', color: colours.primary, textTransform: 'uppercase', letterSpacing: 1.6, marginTop: 2 },
  brandDivider: { width: 32, height: 1.5, backgroundColor: colours.primary + '44', marginVertical: spacing.xs },
  brandTagline: {
    fontSize: typography.sm,
    color: 'rgba(255,255,255,0.4)',
    lineHeight: 20,
  },

  // ── Form elements ─────────────────────────────────────────────────────────────
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.xs,
    backgroundColor: colours.error + '14',
    padding: spacing.md,
    borderRadius: 14,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colours.error + '33',
  },
  errorText: { flex: 1, color: colours.error, fontSize: typography.sm },
  field: { gap: 6, marginBottom: spacing.md },
  fieldLabel: {
    fontSize: typography.xxs,
    fontWeight: '800',
    color: colours.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  input: {
    backgroundColor: colours.white,
    borderWidth: 1.5,
    borderColor: colours.divider,
    borderRadius: 14,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 4,
    fontSize: typography.md,
    color: colours.textOnLight,
    minHeight: 54,
  },
  primaryBtn: {
    backgroundColor: colours.backgroundDark,
    borderRadius: radius.full,
    paddingVertical: spacing.md,
    alignItems: 'center',
    minHeight: 56,
    justifyContent: 'center',
    marginTop: spacing.xs,
    marginBottom: spacing.md,
  },
  primaryBtnDisabled: { opacity: 0.5 },
  primaryBtnText: { color: colours.white, fontSize: typography.md, fontWeight: '800', letterSpacing: 0.3 },
  orRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginBottom: spacing.md },
  orLine: { flex: 1, height: 1, backgroundColor: colours.divider },
  orText: { fontSize: typography.xs, color: colours.textMuted, fontWeight: '500' },
  secondaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    borderWidth: 1.5,
    borderColor: colours.primary,
    borderRadius: radius.full,
    paddingVertical: spacing.sm + 4,
    minHeight: 52,
    backgroundColor: colours.primaryGlow,
    marginBottom: spacing.lg,
  },
  secondaryBtnText: { color: colours.primary, fontSize: typography.sm, fontWeight: '700' },
  footerLink: { color: colours.textMuted, fontSize: typography.sm, textAlign: 'center', paddingVertical: spacing.sm },
  footerLinkBold: { color: colours.primary, fontWeight: '700' },

  // legacy compat
  safe2: { flex: 1, backgroundColor: colours.backgroundDark },
  container: { flex: 1, padding: spacing.lg, justifyContent: 'center' },
  title: { fontSize: 30, fontWeight: '900', color: colours.textOnLight },
  subtitle: { fontSize: typography.sm, color: colours.textMuted },
  button: { backgroundColor: colours.primary, borderRadius: radius.full, padding: spacing.md, alignItems: 'center', minHeight: 54 },
  buttonDisabled: { opacity: 0.5 },
  buttonText: { color: colours.white, fontSize: typography.md, fontWeight: '800' },
  link: { color: colours.primary, fontSize: typography.sm, textAlign: 'center', paddingVertical: spacing.sm, fontWeight: '600' },
  errorBanner2: { backgroundColor: colours.error + '15', color: colours.error, padding: spacing.md, borderRadius: 14, fontSize: typography.sm, marginBottom: spacing.md },
  inputGroup: { gap: spacing.xs, marginBottom: spacing.md },
  inputLabel: { fontSize: typography.xs, fontWeight: '700', color: colours.textMuted },
  outlineButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.xs, borderWidth: 1.5, borderColor: colours.primary, borderRadius: radius.full, paddingVertical: spacing.sm + 4, backgroundColor: colours.primaryGlow },
  outlineButtonText: { color: colours.primary, fontSize: typography.sm, fontWeight: '700' },
  dividerRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  dividerLine: { flex: 1, height: 1, backgroundColor: colours.divider },
  dividerText: { fontSize: typography.xs, color: colours.textMuted },
  linkBold: { color: colours.primary, fontWeight: '700' },
  formScroll: { flex: 1, width: '100%' },
  formCard: { flexGrow: 1, justifyContent: 'center', maxWidth: 440, width: '100%', alignSelf: 'center', padding: spacing.xxl },
});
