import { StyleSheet } from 'react-native';
import { colours } from '../../../shared/theme/colours';
import { spacing } from '../../../shared/theme/spacing';
import { typography } from '../../../shared/theme/typography';
import { radius } from '../../../shared/theme/radius';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colours.backgroundDark },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colours.backgroundDark },
  container: { paddingBottom: spacing.xxl, maxWidth: 860, alignSelf: 'center', width: '100%' },

  // ── Cover ────────────────────────────────────────────────────────────────────
  cover: {
    height: 200,
    backgroundColor: colours.backgroundMid,
    position: 'relative',
    overflow: 'hidden',
    borderBottomWidth: 1,
    borderBottomColor: colours.dividerDark,
  },
  coverImage: { width: '100%', height: '100%' },
  coverPlaceholder: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 8 },
  coverHint: { fontSize: typography.xs, color: 'rgba(255,255,255,0.3)', fontWeight: '500' },
  coverEditBtn: {
    position: 'absolute',
    bottom: spacing.sm,
    right: spacing.sm,
    width: 32,
    height: 32,
    borderRadius: radius.full,
    backgroundColor: 'rgba(0,0,0,0.55)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
  },

  // ── Identity block ───────────────────────────────────────────────────────────
  identityBlock: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    marginTop: -48,
    marginBottom: spacing.md,
  },
  logoWrap: { position: 'relative', flexShrink: 0 },
  logo: {
    width: 96,
    height: 96,
    borderRadius: 20,
    borderWidth: 4,
    borderColor: colours.backgroundDark,
  },
  logoPlaceholder: {
    width: 96,
    height: 96,
    borderRadius: 20,
    backgroundColor: colours.backgroundMid,
    borderWidth: 4,
    borderColor: colours.backgroundDark,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoCameraBtn: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    width: 24,
    height: 24,
    borderRadius: radius.full,
    backgroundColor: colours.primary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: colours.backgroundDark,
  },
  restaurantMeta: {
    flex: 1,
    paddingBottom: 4,
    gap: 4,
  },
  restaurantName: {
    fontSize: typography.xl,
    fontWeight: '900',
    color: colours.textOnDark,
    letterSpacing: -0.5,
  },
  addressRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  addressText: { fontSize: typography.xs, color: 'rgba(255,255,255,0.4)', flex: 1 },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    alignSelf: 'flex-start',
    backgroundColor: colours.primary + '18',
    paddingHorizontal: spacing.sm + 2,
    paddingVertical: 3,
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: colours.primary + '44',
  },
  statusDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colours.primary },
  statusText: { fontSize: typography.xxs, fontWeight: '700', color: colours.primary, textTransform: 'capitalize' },

  description: {
    fontSize: typography.sm,
    color: 'rgba(255,255,255,0.4)',
    lineHeight: 20,
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.md,
  },

  // ── Sections ─────────────────────────────────────────────────────────────────
  section: { paddingHorizontal: spacing.md, marginBottom: spacing.md },
  sectionLabel: {
    fontSize: typography.xxs,
    fontWeight: '800',
    color: 'rgba(255,255,255,0.35)',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    paddingHorizontal: spacing.xs,
    marginBottom: spacing.sm,
  },

  // ── Account card ─────────────────────────────────────────────────────────────
  card: {
    backgroundColor: colours.backgroundMid,
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colours.dividerDark,
  },
  accountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.md,
  },
  accountRowIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  accountRowText: { flex: 1 },
  accountRowLabel: {
    fontSize: typography.xxs,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.35)',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 2,
  },
  accountRowValue: {
    fontSize: typography.sm,
    fontWeight: '600',
    color: colours.textOnDark,
  },
  rowSep: { height: 1, backgroundColor: colours.dividerDark, marginLeft: 38 + spacing.md * 2 },

  // ── Menu row (e.g. Business Profile link) ────────────────────────────────────
  menuRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    backgroundColor: colours.backgroundMid,
    borderRadius: 20,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
    minHeight: 56,
    borderWidth: 1,
    borderColor: colours.dividerDark,
  },
  menuRowLabel: {
    flex: 1,
    fontSize: typography.sm,
    fontWeight: '600',
    color: colours.textOnDark,
  },

  // ── Logout ───────────────────────────────────────────────────────────────────
  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    backgroundColor: colours.backgroundMid,
    borderRadius: 20,
    paddingVertical: spacing.md,
    minHeight: 56,
    borderWidth: 1.5,
    borderColor: colours.error + '33',
  },
  logoutText: { color: colours.error, fontSize: typography.md, fontWeight: '800' },

  // legacy compat (unused but kept to avoid TS errors if referenced elsewhere)
  coverPhotoContainer: { width: '100%', height: 200, backgroundColor: colours.backgroundMid },
  coverPhoto: { width: '100%', height: 200 },
  coverPhotoPlaceholder: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  uploadHint: { fontSize: typography.xs, color: 'rgba(255,255,255,0.3)' },
  logoContainer: { position: 'relative' },
  logo2: { width: 88, height: 88, borderRadius: radius.xl, borderWidth: 3, borderColor: colours.backgroundDark },
  logoPlaceholder2: { width: 88, height: 88, borderRadius: radius.xl, backgroundColor: colours.backgroundMid, borderWidth: 3, borderColor: colours.backgroundDark, alignItems: 'center', justifyContent: 'center' },
  logoEditBadge: { position: 'absolute', bottom: 4, right: 4, width: 22, height: 22, borderRadius: radius.full, backgroundColor: colours.primary, alignItems: 'center', justifyContent: 'center' },
  restaurantInfo: { flex: 1, gap: 4 },
  restaurantName2: { fontSize: typography.xl, fontWeight: '800', color: colours.textOnDark },
  address: { fontSize: typography.xs, color: 'rgba(255,255,255,0.4)' },
  statusBadge: { alignSelf: 'flex-start', backgroundColor: colours.primary + '18', paddingHorizontal: spacing.md, paddingVertical: 3, borderRadius: radius.full },
  accountSection: { backgroundColor: colours.backgroundMid, marginHorizontal: spacing.md, borderRadius: 20, padding: spacing.md, marginBottom: spacing.md, borderWidth: 1, borderColor: colours.dividerDark },
  sectionTitle: { fontSize: typography.xxs, fontWeight: '800', color: 'rgba(255,255,255,0.35)', textTransform: 'uppercase', letterSpacing: 1.2, marginBottom: spacing.sm },
  accountName: { fontSize: typography.md, fontWeight: '700', color: colours.textOnDark },
  accountEmail: { fontSize: typography.sm, color: 'rgba(255,255,255,0.4)' },
  accountPhone: { fontSize: typography.sm, color: 'rgba(255,255,255,0.4)' },
  logoutButton: { marginHorizontal: spacing.md, backgroundColor: colours.backgroundMid, borderWidth: 1.5, borderColor: colours.error + '44', borderRadius: 20, padding: spacing.md, alignItems: 'center', minHeight: 54 },
  logoutText2: { color: colours.error, fontSize: typography.md, fontWeight: '700' },
});
