import { StyleSheet } from 'react-native';
import { colours } from '../../../shared/theme/colours';
import { spacing } from '../../../shared/theme/spacing';
import { typography } from '../../../shared/theme/typography';
import { radius } from '../../../shared/theme/radius';

export const styles = StyleSheet.create({
  safe:    { flex: 1, backgroundColor: colours.surface },
  loading: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colours.surface },

  // ── Header ────────────────────────────────────────────────────────────────
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 2,
    borderBottomWidth: 1,
    borderBottomColor: colours.divider,
    gap: spacing.sm,
  },
  backBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.xs,
    minWidth: 44,
    minHeight: 44,
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    fontSize: typography.md,
    fontWeight: '800',
    color: colours.textOnLight,
    letterSpacing: -0.3,
  },
  headerSubtitle: {
    fontSize: typography.xs,
    color: colours.textSubtle,
    marginTop: 1,
  },
  saveBtn: {
    backgroundColor: colours.primary,
    borderRadius: radius.full,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs + 2,
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 110,
  },
  saveBtnDisabled: { opacity: 0.45 },
  saveBtnText: {
    color: colours.surface,
    fontSize: typography.xs,
    fontWeight: '800',
  },

  // ── Scroll ────────────────────────────────────────────────────────────────
  scroll: { flex: 1 },
  scrollContent: {
    padding: spacing.md,
    gap: spacing.md,
    maxWidth: 720,
    width: '100%',
    alignSelf: 'center',
    paddingBottom: spacing.xxl,
  },

  // ── Section card ──────────────────────────────────────────────────────────
  card: {
    backgroundColor: colours.surfaceMuted,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colours.divider,
    padding: spacing.md,
    gap: spacing.sm,
  },
  sectionLabel: {
    fontSize: typography.xxs,
    fontWeight: '800',
    color: colours.textMuted,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 2,
  },

  // ── Photo ─────────────────────────────────────────────────────────────────
  photoWrap: { position: 'relative', borderRadius: radius.md, overflow: 'hidden' },
  photo:     { width: '100%', height: 200, backgroundColor: colours.surfaceMuted },
  noPhoto: {
    width: '100%',
    height: 120,
    backgroundColor: colours.surfaceMuted,
    borderWidth: 1.5,
    borderColor: colours.divider,
    borderStyle: 'dashed',
    borderRadius: radius.md,
    justifyContent: 'center',
    alignItems: 'center',
    gap: spacing.xs,
  },
  noPhotoText: { fontSize: typography.xs, color: colours.textSubtle },
  newBadge: {
    position: 'absolute',
    top: 8,
    left: 8,
    backgroundColor: colours.primary,
    borderRadius: radius.full,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  newBadgeText: { fontSize: typography.xxs, color: colours.surface, fontWeight: '800' },
  changePhotoBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    borderWidth: 1,
    borderColor: colours.primary,
    borderRadius: radius.full,
    paddingVertical: spacing.xs + 2,
    minHeight: 36,
    backgroundColor: colours.primary + '18',
  },
  changePhotoBtnText: { fontSize: typography.xs, color: colours.primary, fontWeight: '700' },

  // ── Form fields ───────────────────────────────────────────────────────────
  fieldLabel: {
    fontSize: typography.xs,
    fontWeight: '600',
    color: colours.textMuted,
    marginBottom: 4,
  },
  input: {
    backgroundColor: colours.surface,
    borderWidth: 1,
    borderColor: colours.divider,
    borderRadius: radius.md,
    paddingHorizontal: spacing.sm + 2,
    paddingVertical: spacing.sm,
    fontSize: typography.sm,
    color: colours.textOnLight,
    minHeight: 44,
  },
  inputMultiline: {
    minHeight: 80,
    textAlignVertical: 'top',
  },

  // ── Pricing ───────────────────────────────────────────────────────────────
  priceRow: { flexDirection: 'row', gap: spacing.sm },
  priceCol: { flex: 1, gap: 4 },
  customerSeesRow: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 3 },
  customerSeesLabel: { fontSize: typography.xxs, color: colours.textSubtle, fontWeight: '600' },
  customerSeesValue: { fontSize: typography.xs, color: colours.primary, fontWeight: '800' },
  discountBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: colours.success + '22',
    borderWidth: 1,
    borderColor: colours.success + '44',
    borderRadius: radius.full,
    paddingHorizontal: spacing.sm,
    paddingVertical: 5,
    alignSelf: 'flex-start',
  },
  discountText: { fontSize: typography.xs, color: colours.success, fontWeight: '700' },

  // ── Options ───────────────────────────────────────────────────────────────
  addGroupBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: colours.primary,
    backgroundColor: colours.primary + '18',
    alignSelf: 'flex-start',
  },
  addGroupBtnText: { fontSize: typography.xs, color: colours.primary, fontWeight: '700' },
  groupCard: {
    backgroundColor: colours.surface,
    borderWidth: 1,
    borderColor: colours.divider,
    borderRadius: radius.md,
    padding: spacing.sm,
    gap: spacing.xs,
  },
  groupHeader: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  groupMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    flexWrap: 'wrap',
  },
  metaItem: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  metaLabel: { fontSize: typography.xxs, color: colours.textMuted, fontWeight: '600' },
  numInput: {
    borderWidth: 1,
    borderColor: colours.divider,
    borderRadius: radius.sm,
    paddingHorizontal: 6,
    paddingVertical: 3,
    fontSize: typography.sm,
    color: colours.textOnLight,
    width: 40,
    textAlign: 'center',
    backgroundColor: colours.surfaceMuted,
  },
  optionRow: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  optionNameInput: { flex: 2 },
  optionPriceInput: { flex: 1 },
  addOptionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingVertical: 3,
    alignSelf: 'flex-start',
  },
  addOptionText: { fontSize: typography.xs, color: colours.primary, fontWeight: '700' },
  iconBtn: { padding: 6, minWidth: 32, alignItems: 'center' },
  errorBanner: {
    backgroundColor: colours.error,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  errorBannerText: {
    color: colours.surface,
    fontSize: typography.sm,
    fontWeight: '600',
  },
});
