import { StyleSheet } from 'react-native';
import { colours } from '@/shared/theme/colours';
import { radius } from '@/shared/theme/radius';
import { spacing } from '@/shared/theme/spacing';
import { typography } from '@/shared/theme/typography';

export const styles = StyleSheet.create({
  root:  { flex: 1, backgroundColor: colours.backgroundDark },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    gap: spacing.sm,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: typography.lg,
    fontWeight: '800',
    color: colours.textOnDark,
    flex: 1,
  },
  keyboardAvoid: { flex: 1 },
  scroll:        { flex: 1, backgroundColor: colours.backgroundLight },
  content:  { padding: spacing.md, gap: spacing.sm, paddingBottom: spacing.xxl },
  sectionLabel: {
    fontSize: typography.xxs,
    fontWeight: '700',
    color: colours.textMuted,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginTop: spacing.sm,
    lineHeight: 27,
  },
  required: { color: colours.danger },
  pillRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: 4,
  },
  pill: {
    flex: 1,
    paddingVertical: spacing.sm,
    borderRadius: radius.xl,
    borderWidth: 1.5,
    borderColor: colours.divider,
    backgroundColor: colours.card,
    alignItems: 'center',
  },
  pillActive: {
    backgroundColor: colours.primary,
    borderColor: colours.primary,
  },
  pillText: {
    fontSize: typography.sm,
    fontWeight: '600',
    color: colours.textMuted,
    lineHeight: 39,
  },
  pillTextActive: { color: colours.white },
  input: {
    backgroundColor: colours.card,
    borderRadius: radius.xl,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 2,
    fontSize: typography.sm,
    color: colours.textOnLight,
    borderWidth: 1.5,
    borderColor: 'transparent',
    minHeight: 48,
  },
  inputError: { borderColor: colours.danger },
  errorText: {
    fontSize: typography.xs,
    color: colours.danger,
    marginTop: -spacing.xs,
    lineHeight: 33,
  },
  mapBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: colours.infoBg,
    borderRadius: radius.xl,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 2,
    borderWidth: 1,
    borderColor: colours.infoBorder,
    minHeight: 48,
  },
  mapBtnText: {
    flex: 1,
    fontSize: typography.sm,
    fontWeight: '600',
    color: colours.primary,
  },
  coordBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: spacing.sm,
    marginTop: -spacing.xs,
  },
  coordText: {
    flex: 1,
    fontSize: typography.xs,
    color: colours.success,
    fontWeight: '500',
  },
  defaultRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.sm,
    marginTop: spacing.xs,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: colours.divider,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colours.card,
  },
  checkboxActive: {
    backgroundColor: colours.primary,
    borderColor: colours.primary,
  },
  defaultLabel: {
    fontSize: typography.sm,
    fontWeight: '500',
    color: colours.textOnLight,
    lineHeight: 39,
  },
  saveBtn: {
    backgroundColor: colours.primary,
    borderRadius: radius.xl,
    paddingVertical: spacing.md,
    alignItems: 'center',
    marginTop: spacing.sm,
  },
  saveBtnDisabled: { opacity: 0.5 },
  saveBtnText: {
    fontSize: typography.md,
    fontWeight: '700',
    color: colours.white,
    letterSpacing: 0.3,
  },
});
