import { StyleSheet } from 'react-native';
import { colours } from '../../../shared/theme/colours';
import { spacing } from '../../../shared/theme/spacing';
import { typography } from '../../../shared/theme/typography';
import { radius } from '../../../shared/theme/radius';

const floatingCard = {
  backgroundColor: colours.surface,
  borderRadius: radius.xl,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.06,
  shadowRadius: 10,
  elevation: 3,
};

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colours.backgroundDark,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 2,
    backgroundColor: colours.backgroundDark,
    gap: spacing.sm,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: radius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  topBarTitle: {
    flex: 1,
    fontSize: typography.md,
    fontWeight: '700',
    color: colours.textOnDark,
    letterSpacing: -0.2,
  },
  scroll: {
    flex: 1,
    backgroundColor: colours.backgroundLight,
  },
  scrollContent: {
    padding: spacing.md,
    paddingBottom: spacing.xl,
    gap: spacing.md,
    maxWidth: 860,
    alignSelf: 'center',
    width: '100%',
  },
  card: {
    ...floatingCard,
    overflow: 'hidden',
  },
  cardHeader: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 2,
    backgroundColor: colours.backgroundDark,
    borderBottomWidth: 0,
  },
  cardTitle: {
    fontSize: typography.xxs,
    fontWeight: '800',
    color: 'rgba(255,255,255,0.5)',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  cardBody: {
    padding: spacing.md,
    gap: spacing.sm,
  },
  orderHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  orderNumber: {
    fontSize: typography.xl,
    fontWeight: '800',
    color: colours.textOnLight,
    letterSpacing: -0.5,
  },
  statusBadge: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: radius.full,
  },
  statusText: {
    fontSize: typography.xxs,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  divider: {
    height: 1,
    backgroundColor: colours.divider,
    marginVertical: spacing.xs,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: spacing.sm,
  },
  label: {
    fontSize: typography.sm,
    color: colours.textMuted,
    flexShrink: 0,
  },
  value: {
    fontSize: typography.sm,
    fontWeight: '600',
    color: colours.textOnLight,
    flex: 1,
    textAlign: 'right',
  },
  itemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingVertical: spacing.xs + 2,
    gap: spacing.sm,
  },
  itemNameCol: {
    flex: 1,
    gap: 2,
  },
  itemName: {
    fontSize: typography.sm,
    fontWeight: '600',
    color: colours.textOnLight,
  },
  itemQty: {
    fontSize: typography.xs,
    color: colours.textMuted,
  },
  itemNotes: {
    fontSize: typography.xs,
    color: colours.textMuted,
    fontStyle: 'italic',
  },
  itemPrice: {
    fontSize: typography.sm,
    fontWeight: '700',
    color: colours.textOnLight,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: spacing.sm,
    marginTop: spacing.xs,
    borderTopWidth: 1.5,
    borderTopColor: colours.divider,
  },
  totalLabel: {
    fontSize: typography.md,
    fontWeight: '800',
    color: colours.textOnLight,
  },
  totalValue: {
    fontSize: typography.md,
    fontWeight: '800',
    color: colours.primary,
  },
  actionButton: {
    backgroundColor: colours.primary,
    borderRadius: radius.full,
    paddingVertical: spacing.md,
    alignItems: 'center',
    marginTop: spacing.xs,
    maxWidth: 400,
    alignSelf: 'center',
    width: '100%',
  },
  actionButtonDisabled: {
    opacity: 0.5,
  },
  actionButtonText: {
    color: colours.white,
    fontSize: typography.md,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  cancelButton: {
    backgroundColor: colours.surface,
    borderRadius: radius.full,
    paddingVertical: spacing.sm + 4,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: colours.error + '55',
    maxWidth: 400,
    alignSelf: 'center',
    width: '100%',
  },
  cancelButtonText: {
    color: colours.error,
    fontSize: typography.sm,
    fontWeight: '700',
  },
  infoNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    backgroundColor: colours.warningBg,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 2,
    borderWidth: 1,
    borderColor: colours.warning + '33',
  },
  infoNoteText: {
    flex: 1,
    fontSize: typography.sm,
    color: colours.warning,
    fontWeight: '500',
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colours.backgroundLight,
    gap: spacing.sm,
  },
  errorText: {
    fontSize: typography.sm,
    color: colours.error,
  },
  // Cancel reason modal
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: colours.surface,
    borderTopLeftRadius: radius.sheet,
    borderTopRightRadius: radius.sheet,
    padding: spacing.lg,
    gap: spacing.md,
    paddingBottom: spacing.xxl,
  },
  modalTitle: {
    fontSize: typography.xl,
    fontWeight: '800',
    color: colours.textOnLight,
    letterSpacing: -0.4,
  },
  modalLabel: {
    fontSize: typography.xxs,
    fontWeight: '700',
    color: colours.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: spacing.xs,
  },
  reasonOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.sm + 2,
    gap: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colours.divider,
  },
  reasonOptionText: {
    flex: 1,
    fontSize: typography.sm,
    color: colours.textOnLight,
  },
  radioOuter: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: colours.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioInner: {
    width: 11,
    height: 11,
    borderRadius: 6,
    backgroundColor: colours.primary,
  },
  modalTextInput: {
    borderWidth: 1.5,
    borderColor: colours.divider,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontSize: typography.sm,
    color: colours.textOnLight,
    minHeight: 80,
    textAlignVertical: 'top',
    backgroundColor: colours.surfaceMuted,
  },
  modalActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  modalCancelBtn: {
    flex: 1,
    borderWidth: 1.5,
    borderColor: colours.divider,
    borderRadius: radius.full,
    paddingVertical: spacing.sm + 4,
    alignItems: 'center',
  },
  modalCancelText: {
    color: colours.textMuted,
    fontSize: typography.sm,
    fontWeight: '600',
  },
  modalConfirmBtn: {
    flex: 1,
    backgroundColor: colours.error,
    borderRadius: radius.full,
    paddingVertical: spacing.sm + 4,
    alignItems: 'center',
  },
  modalConfirmText: {
    color: colours.white,
    fontSize: typography.sm,
    fontWeight: '700',
  },
  chatButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    backgroundColor: colours.primaryGlow,
    borderRadius: radius.full,
    paddingVertical: spacing.sm + 4,
    borderWidth: 1.5,
    borderColor: colours.primary,
    marginTop: spacing.xs,
    maxWidth: 400,
    alignSelf: 'center',
    width: '100%',
  },
  chatButtonText: {
    color: colours.primary,
    fontSize: typography.sm,
    fontWeight: '700',
  },
});
