import { StyleSheet } from 'react-native';
import { colours } from '../../../shared/theme/colours';
import { spacing } from '../../../shared/theme/spacing';
import { typography } from '../../../shared/theme/typography';
import { radius } from '../../../shared/theme/radius';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colours.backgroundDark },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colours.backgroundDark, gap: spacing.sm },
  errorText: { fontSize: typography.sm, color: colours.error },

  // ── Top bar ──────────────────────────────────────────────────────────────────
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 2,
    backgroundColor: colours.backgroundDark,
    borderBottomWidth: 1,
    borderBottomColor: colours.dividerDark,
    gap: spacing.sm,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: radius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colours.backgroundMid,
    borderWidth: 1,
    borderColor: colours.dividerDark,
  },
  topBarTitle: { flex: 1, fontSize: typography.md, fontWeight: '700', color: colours.textOnDark },
  statusBadge: { paddingHorizontal: spacing.md, paddingVertical: spacing.xs, borderRadius: radius.full },
  statusText: { fontSize: typography.xxs, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.5 },

  // ── Scroll ────────────────────────────────────────────────────────────────────
  scroll: { flex: 1 },
  scrollContent: {
    padding: spacing.md,
    gap: spacing.md,
    paddingBottom: spacing.xxl,
    maxWidth: 860,
    alignSelf: 'center',
    width: '100%',
  },

  // ── Cards ─────────────────────────────────────────────────────────────────────
  card: {
    backgroundColor: colours.backgroundMid,
    borderRadius: radius.xl,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colours.dividerDark,
  },
  cardHeader: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 2,
    backgroundColor: colours.backgroundDark,
    borderBottomWidth: 1,
    borderBottomColor: colours.dividerDark,
  },
  cardTitle: {
    fontSize: typography.xxs,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.45)',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  cardBody: { padding: spacing.md, gap: spacing.sm },

  // ── Info rows ─────────────────────────────────────────────────────────────────
  orderHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  orderNumber: { fontSize: typography.lg, fontWeight: '800', color: colours.textOnDark, letterSpacing: -0.3 },
  divider: { height: 1, backgroundColor: colours.dividerDark },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: spacing.sm },
  label: { fontSize: typography.sm, color: 'rgba(255,255,255,0.4)', flexShrink: 0 },
  value: { fontSize: typography.sm, fontWeight: '500', color: colours.textOnDark, flex: 1, textAlign: 'right' },

  // ── Items ─────────────────────────────────────────────────────────────────────
  itemRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', paddingVertical: spacing.xs + 2, gap: spacing.sm },
  itemNameCol: { flex: 1, gap: 2 },
  itemName: { fontSize: typography.sm, fontWeight: '600', color: colours.textOnDark },
  itemQty: { fontSize: typography.xs, color: 'rgba(255,255,255,0.4)' },
  itemNotes: { fontSize: typography.xs, color: 'rgba(255,255,255,0.3)', fontStyle: 'italic' },
  itemPrice: { fontSize: typography.sm, fontWeight: '700', color: colours.textOnDark },
  totalRow: { flexDirection: 'row', justifyContent: 'space-between', paddingTop: spacing.sm, marginTop: spacing.xs, borderTopWidth: 1.5, borderTopColor: colours.dividerDark },
  totalLabel: { fontSize: typography.md, fontWeight: '800', color: colours.textOnDark },
  totalValue: { fontSize: typography.md, fontWeight: '800', color: colours.primary },

  // ── Actions ───────────────────────────────────────────────────────────────────
  actionButton: {
    backgroundColor: colours.primary,
    borderRadius: radius.full,
    paddingVertical: spacing.md,
    alignItems: 'center',
    maxWidth: 480,
    alignSelf: 'center',
    width: '100%',
  },
  actionButtonDisabled: { opacity: 0.5 },
  actionButtonText: { color: colours.backgroundDark, fontSize: typography.md, fontWeight: '800', letterSpacing: 0.3 },
  cancelButton: {
    backgroundColor: colours.backgroundMid,
    borderRadius: radius.full,
    paddingVertical: spacing.sm + 4,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: colours.error + '55',
    maxWidth: 480,
    alignSelf: 'center',
    width: '100%',
  },
  cancelButtonText: { color: colours.error, fontSize: typography.sm, fontWeight: '700' },
  chatButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    backgroundColor: colours.primary + '18',
    borderRadius: radius.full,
    paddingVertical: spacing.sm + 4,
    borderWidth: 1.5,
    borderColor: colours.primary,
    maxWidth: 480,
    alignSelf: 'center',
    width: '100%',
  },
  chatButtonText: { color: colours.primary, fontSize: typography.sm, fontWeight: '700' },
  infoNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    backgroundColor: colours.warning + '18',
    borderRadius: radius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 2,
    borderWidth: 1,
    borderColor: colours.warning + '33',
  },
  infoNoteText: { flex: 1, fontSize: typography.sm, color: colours.warning, fontWeight: '500' },

  // ── Cancel modal ──────────────────────────────────────────────────────────────
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.65)', justifyContent: 'flex-end' },
  modalCard: {
    backgroundColor: colours.backgroundMid,
    borderTopLeftRadius: radius.sheet,
    borderTopRightRadius: radius.sheet,
    padding: spacing.lg,
    gap: spacing.md,
    paddingBottom: spacing.xxl,
    borderWidth: 1,
    borderColor: colours.dividerDark,
  },
  modalTitle: { fontSize: typography.xl, fontWeight: '800', color: colours.textOnDark, letterSpacing: -0.4 },
  modalLabel: { fontSize: typography.xxs, fontWeight: '700', color: 'rgba(255,255,255,0.4)', textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: spacing.xs },
  reasonOption: { flexDirection: 'row', alignItems: 'center', paddingVertical: spacing.sm + 2, gap: spacing.sm, borderBottomWidth: 1, borderBottomColor: colours.dividerDark },
  reasonOptionText: { flex: 1, fontSize: typography.sm, color: colours.textOnDark },
  radioOuter: { width: 22, height: 22, borderRadius: 11, borderWidth: 2, borderColor: colours.primary, alignItems: 'center', justifyContent: 'center' },
  radioInner: { width: 11, height: 11, borderRadius: 6, backgroundColor: colours.primary },
  modalTextInput: {
    borderWidth: 1.5,
    borderColor: colours.dividerDark,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontSize: typography.sm,
    color: colours.textOnDark,
    minHeight: 80,
    textAlignVertical: 'top',
    backgroundColor: colours.backgroundDark,
  },
  modalActions: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.xs },
  modalCancelBtn: { flex: 1, borderWidth: 1.5, borderColor: colours.dividerDark, borderRadius: radius.full, paddingVertical: spacing.sm + 4, alignItems: 'center' },
  modalCancelText: { color: 'rgba(255,255,255,0.4)', fontSize: typography.sm, fontWeight: '600' },
  modalConfirmBtn: { flex: 1, backgroundColor: colours.error, borderRadius: radius.full, paddingVertical: spacing.sm + 4, alignItems: 'center' },
  modalConfirmText: { color: colours.white, fontSize: typography.sm, fontWeight: '700' },
});
