export const MAP_COLORS = {
  primary:       '#224e4a',
  primaryDark:   '#163533',
  primaryLight:  '#e0eeec',
  background:    '#f8fafc',
  surface:       '#ffffff',
  surfaceAlt:    '#f1f5f4',
  textPrimary:   '#0f1f1e',
  textSecondary: '#5f6d6c',
  textMuted:     '#8fa3a1',
  textOnPrimary: '#ffffff',
  border:        '#d1dbd9',
  success:       '#15803d',
  successLight:  '#dcfce7',
  error:         '#dc2626',
  errorLight:    '#fee2e2',
  white:         '#ffffff',
  black:         '#000000',
  transparent:   'transparent',
} as const;

export const CATEGORY_EMOJI: Record<string, string> = {
  restaurant:    '🍽',
  food:          '🍽',
  attraction:    '🎯',
  hotel:         '🏨',
  accommodation: '🏨',
  cafe:          '☕',
  coffee:        '☕',
  shopping:      '🛍',
  mall:          '🛍',
  temple:        '🛕',
  park:          '🌿',
  beach:         '🏖',
  museum:        '🏛',
  office:        '🏢',
  immigration:   '🛂',
  embassy:       '🏛',
  default:       '📍',
};
