import { StyleSheet } from 'react-native';
import { colours } from '../../../shared/theme/colours';
import { spacing } from '../../../shared/theme/spacing';
import { typography } from '../../../shared/theme/typography';
import { radius } from '../../../shared/theme/radius';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colours.backgroundLight,
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colours.backgroundLight,
  },
  list: {
    padding: spacing.md,
  },
  addButton: {
    backgroundColor: colours.primary,
    borderRadius: radius.md,
    padding: spacing.md,
    alignItems: 'center',
    marginBottom: spacing.md,
    minHeight: 44,
    justifyContent: 'center',
  },
  addButtonText: {
    color: colours.white,
    fontSize: typography.md,
    fontWeight: '600',
  },
  empty: {
    textAlign: 'center',
    color: colours.medium,
    fontSize: typography.md,
    marginTop: spacing.xxl,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: colours.textOnLight + '88',
    justifyContent: 'center',
    padding: spacing.lg,
  },
  modalCard: {
    backgroundColor: colours.card,
    borderRadius: radius.sheet,
    padding: spacing.lg,
  },
  modalTitle: {
    fontSize: typography.lg,
    fontWeight: '700',
    color: colours.textOnLight,
    marginBottom: spacing.md,
  },
  modalInput: {
    backgroundColor: colours.backgroundLight,
    borderWidth: 1,
    borderColor: colours.divider,
    borderRadius: radius.md,
    padding: spacing.md,
    fontSize: typography.md,
    color: colours.textOnLight,
    marginBottom: spacing.md,
    minHeight: 44,
  },
  modalActions: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  cancelButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: colours.divider,
    borderRadius: radius.md,
    padding: spacing.md,
    alignItems: 'center',
    minHeight: 44,
    justifyContent: 'center',
  },
  cancelText: {
    color: colours.textMuted,
    fontSize: typography.md,
  },
  confirmButton: {
    flex: 1,
    backgroundColor: colours.primary,
    borderRadius: radius.md,
    padding: spacing.md,
    alignItems: 'center',
    minHeight: 44,
    justifyContent: 'center',
  },
  confirmText: {
    color: colours.white,
    fontSize: typography.md,
    fontWeight: '600',
  },
  modalScrollView: {
    maxHeight: '90%',
  },
  priceRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  priceLabel: {
    fontSize: typography.xs,
    color: colours.textMuted,
    fontWeight: '600',
    marginBottom: 4,
  },
  discountBadge: {
    fontSize: typography.xs,
    color: colours.success,
    fontWeight: '600',
    marginBottom: spacing.sm,
    marginTop: -spacing.xs,
  },
  sectionDivider: {
    height: 1,
    backgroundColor: colours.divider,
    marginVertical: spacing.md,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  sectionTitle: {
    fontSize: typography.sm,
    fontWeight: '700',
    color: colours.textOnLight,
  },
  sectionHint: {
    fontSize: typography.xxs,
    color: colours.textMuted,
    marginBottom: spacing.sm,
  },
  addSmallBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colours.primary,
  },
  addSmallBtnText: {
    fontSize: typography.xs,
    color: colours.primary,
    fontWeight: '600',
  },
  optionGroupCard: {
    borderWidth: 1,
    borderColor: colours.divider,
    borderRadius: radius.md,
    padding: spacing.sm,
    marginBottom: spacing.sm,
    backgroundColor: colours.surfaceMuted,
  },
  optionGroupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: spacing.xs,
  },
  optionGroupMeta: {
    flexDirection: 'row',
    gap: spacing.md,
    marginBottom: spacing.sm,
    alignItems: 'center',
  },
  toggleRowSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  toggleLabelSmall: {
    fontSize: typography.xs,
    color: colours.textMuted,
  },
  smallNumInput: {
    borderWidth: 1,
    borderColor: colours.divider,
    borderRadius: radius.sm,
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: typography.sm,
    color: colours.textOnLight,
    width: 40,
    textAlign: 'center',
    backgroundColor: colours.surface,
  },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 6,
  },
  addOptionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 4,
    alignSelf: 'flex-start',
  },
  addOptionBtnText: {
    fontSize: typography.xs,
    color: colours.primary,
    fontWeight: '600',
  },
  photoPreviewWrap: {
    position: 'relative',
    marginBottom: spacing.sm,
    borderRadius: radius.md,
    overflow: 'hidden',
  },
  photoPreview: {
    width: '100%',
    height: 160,
    borderRadius: radius.md,
    backgroundColor: colours.backgroundLight,
  },
  photoNewBadge: {
    position: 'absolute',
    top: 6,
    left: 6,
    backgroundColor: colours.primary,
    borderRadius: radius.full,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  photoNewBadgeText: {
    fontSize: typography.xxs,
    color: colours.white,
    fontWeight: '700',
  },
  photoActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  photoErrorState: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colours.surfaceMuted,
    borderWidth: 1,
    borderColor: colours.divider,
    borderStyle: 'dashed',
    gap: 6,
  },
  photoErrorText: {
    fontSize: typography.xs,
    color: colours.medium,
  },
  warnBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: colours.warningBg,
    borderWidth: 1,
    borderColor: colours.warning + '55',
    borderRadius: radius.md,
    padding: spacing.md,
    marginBottom: spacing.md,
    gap: spacing.sm,
  },
  warnText: {
    flex: 1,
    fontSize: typography.xs,
    color: colours.warning,
    lineHeight: 18,
    fontWeight: '500',
  },
  photoChangeBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: colours.primary,
    borderRadius: radius.md,
    paddingVertical: spacing.sm,
    minHeight: 44,
  },
  photoChangeBtnText: {
    fontSize: typography.sm,
    color: colours.primary,
    fontWeight: '600',
  },
});
