import { StyleSheet } from 'react-native';
import { colours } from '../../../shared/theme/colours';
import { spacing } from '../../../shared/theme/spacing';
import { typography } from '../../../shared/theme/typography';
import { radius } from '../../../shared/theme/radius';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colours.surface },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colours.surface },
  // ── Page header ──────────────────────────────────────────────────────────────
  pageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colours.divider,
    backgroundColor: colours.surface,
  },
  pageTitle: {
    fontSize: typography.display,
    fontWeight: '800',
    color: colours.textOnLight,
    letterSpacing: -0.8,
  },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs + 4,
    borderRadius: radius.full,
    backgroundColor: colours.primary,
    minHeight: 36,
    justifyContent: 'center',
  },
  addButtonText: { color: colours.backgroundDark, fontSize: typography.sm, fontWeight: '700' },
  list: { padding: spacing.lg, width: '100%' },
  empty: { textAlign: 'center', color: colours.textSubtle, fontSize: typography.md, marginTop: spacing.xxl },

  // ── Modal (keep dark — overlays work well dark) ────────────────────────────────
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'flex-end' },
  modalCard: {
    backgroundColor: colours.backgroundMid,
    borderTopLeftRadius: radius.sheet,
    borderTopRightRadius: radius.sheet,
    padding: spacing.lg,
    maxWidth: 560,
    width: '100%',
    alignSelf: 'center',
  },
  modalTitle: { fontSize: typography.xl, fontWeight: '800', color: colours.textOnDark, marginBottom: spacing.md, letterSpacing: -0.4 },
  modalInput: {
    backgroundColor: colours.backgroundDark,
    borderWidth: 1,
    borderColor: colours.dividerDark,
    borderRadius: radius.lg,
    padding: spacing.md,
    fontSize: typography.md,
    color: colours.textOnDark,
    marginBottom: spacing.md,
    minHeight: 48,
  },
  modalActions: { flexDirection: 'row', gap: spacing.sm, justifyContent: 'flex-end', marginTop: spacing.xs },
  cancelButton: { borderWidth: 1, borderColor: colours.dividerDark, borderRadius: radius.full, paddingVertical: spacing.xs + 2, paddingHorizontal: spacing.lg, alignItems: 'center', minHeight: 40, justifyContent: 'center' },
  cancelText: { color: 'rgba(255,255,255,0.5)', fontSize: typography.sm, fontWeight: '600' },
  confirmButton: { backgroundColor: colours.primary, borderRadius: radius.full, paddingVertical: spacing.xs + 2, paddingHorizontal: spacing.lg, alignItems: 'center', minHeight: 40, justifyContent: 'center' },
  confirmText: { color: colours.backgroundDark, fontSize: typography.sm, fontWeight: '700' },
  modalScrollView: { maxHeight: '90%' },
  priceRow: { flexDirection: 'row', gap: spacing.sm },
  priceLabel: { fontSize: typography.xs, color: 'rgba(255,255,255,0.45)', fontWeight: '600', marginBottom: 4 },
  discountBadge: { fontSize: typography.xs, color: colours.success, fontWeight: '700', marginBottom: spacing.sm },
  sectionDivider: { height: 1, backgroundColor: colours.dividerDark, marginVertical: spacing.md },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4 },
  sectionTitle: { fontSize: typography.sm, fontWeight: '700', color: colours.textOnDark },
  sectionHint: { fontSize: typography.xxs, color: 'rgba(255,255,255,0.35)', marginBottom: spacing.sm },
  addSmallBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: spacing.sm, paddingVertical: 4, borderRadius: radius.full, borderWidth: 1, borderColor: colours.primary, backgroundColor: colours.primary + '18' },
  addSmallBtnText: { fontSize: typography.xs, color: colours.primary, fontWeight: '700' },
  optionGroupCard: { borderWidth: 1, borderColor: colours.dividerDark, borderRadius: radius.md, padding: spacing.sm, marginBottom: spacing.sm, backgroundColor: colours.backgroundDark },
  optionGroupHeader: { flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: spacing.xs },
  optionGroupMeta: { flexDirection: 'row', gap: spacing.md, marginBottom: spacing.sm, alignItems: 'center' },
  toggleRowSmall: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  toggleLabelSmall: { fontSize: typography.xs, color: 'rgba(255,255,255,0.45)' },
  smallNumInput: { borderWidth: 1, borderColor: colours.dividerDark, borderRadius: radius.sm, paddingHorizontal: 8, paddingVertical: 4, fontSize: typography.sm, color: colours.textOnDark, width: 44, textAlign: 'center', backgroundColor: colours.backgroundDark },
  optionRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: 6 },
  addOptionBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingVertical: 4, alignSelf: 'flex-start' },
  addOptionBtnText: { fontSize: typography.xs, color: colours.primary, fontWeight: '700' },
  photoPreviewWrap: { position: 'relative', marginBottom: spacing.sm, borderRadius: radius.md, overflow: 'hidden' },
  photoPreview: { width: '100%', height: 160, borderRadius: radius.md, backgroundColor: colours.backgroundDark },
  photoNewBadge: { position: 'absolute', top: 8, left: 8, backgroundColor: colours.primary, borderRadius: radius.full, paddingHorizontal: 8, paddingVertical: 2 },
  photoNewBadgeText: { fontSize: typography.xxs, color: colours.backgroundDark, fontWeight: '800' },
  photoActions: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.sm },
  photoErrorState: { justifyContent: 'center', alignItems: 'center', backgroundColor: colours.backgroundDark, borderWidth: 1, borderColor: colours.dividerDark, borderStyle: 'dashed', gap: 6, borderRadius: radius.md },
  photoErrorText: { fontSize: typography.xs, color: 'rgba(255,255,255,0.3)' },
  warnBanner: { flexDirection: 'row', alignItems: 'flex-start', backgroundColor: colours.warning + '18', borderWidth: 1, borderColor: colours.warning + '44', borderRadius: radius.md, padding: spacing.md, marginBottom: spacing.md, gap: spacing.sm },
  warnText: { flex: 1, fontSize: typography.xs, color: colours.warning, lineHeight: 18, fontWeight: '600' },
  photoChangeBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, borderWidth: 1, borderColor: colours.primary, borderRadius: radius.full, paddingVertical: spacing.sm, minHeight: 44, backgroundColor: colours.primary + '18' },
  photoChangeBtnText: { fontSize: typography.sm, color: colours.primary, fontWeight: '700' },
});
