import { StyleSheet } from 'react-native';
import { colours } from '../../../shared/theme/colours';
import { spacing } from '../../../shared/theme/spacing';
import { typography } from '../../../shared/theme/typography';
import { radius } from '../../../shared/theme/radius';

export const styles = StyleSheet.create({
  card: {
    backgroundColor: colours.surface,
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: colours.divider,
    marginHorizontal: spacing.md,
    marginTop: spacing.md,
    overflow: 'hidden',
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colours.divider,
  },
  cardTitle: {
    fontSize: typography.sm,
    fontWeight: '700',
    color: colours.textOnLight,
    letterSpacing: -0.2,
  },
  editBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: spacing.sm,
    paddingVertical: 5,
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: colours.primaryLight,
    backgroundColor: colours.primaryBg,
  },
  editBtnText: {
    fontSize: typography.xs,
    fontWeight: '700',
    color: colours.primaryDark,
  },
  body: {
    padding: spacing.md,
    gap: 0,
  },
  divider: {
    height: 1,
    backgroundColor: colours.divider,
    marginVertical: spacing.sm,
  },
  infoRow: {
    gap: 3,
  },
  infoLabel: {
    fontSize: typography.xxs,
    fontWeight: '700',
    color: colours.textSubtle,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  infoValue: {
    fontSize: typography.sm,
    color: colours.textOnLight,
    lineHeight: 22,
  },
  infoRowAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  infoRowFlex: { flex: 1 },
  inlineEditBtn: {
    width: 32,
    height: 32,
    borderRadius: radius.full,
    backgroundColor: colours.primaryBg,
    borderWidth: 1,
    borderColor: colours.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fieldWrap: {
    gap: spacing.xs,
  },
  fieldLabel: {
    fontSize: typography.xxs,
    fontWeight: '700',
    color: colours.textSubtle,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: colours.surfaceMuted,
    borderWidth: 1,
    borderColor: colours.divider,
    borderRadius: radius.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    fontSize: typography.sm,
    color: colours.textOnLight,
  },
  inputMultiline: {
    minHeight: 72,
    textAlignVertical: 'top',
  },
  formActions: {
    flexDirection: 'row',
    gap: spacing.xs,
    marginTop: 4,
  },
  cancelBtn: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
    borderRadius: radius.full,
    borderWidth: 1.5,
    borderColor: colours.divider,
  },
  cancelBtnText: {
    fontSize: typography.xs,
    fontWeight: '700',
    color: colours.textMuted,
  },
  saveBtn: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
    borderRadius: radius.full,
    backgroundColor: colours.primary,
  },
  saveBtnDisabled: { opacity: 0.4 },
  saveBtnText: {
    fontSize: typography.xs,
    fontWeight: '700',
    color: colours.backgroundDark,
  },
  locationPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: colours.primaryBg,
    borderRadius: radius.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
  },
  locationPreviewText: {
    fontSize: typography.xs,
    color: colours.primaryDark,
    fontWeight: '600',
  },
  locationEmpty: {
    fontSize: typography.xs,
    color: colours.textSubtle,
    fontStyle: 'italic',
  },
  locationError: {
    fontSize: typography.xs,
    color: colours.error,
    fontWeight: '600',
  },
  locationActions: {
    flexDirection: 'row',
    gap: spacing.xs,
  },
  locationGetBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: spacing.sm,
    paddingVertical: 7,
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: colours.primaryLight,
    backgroundColor: colours.primaryBg,
  },
  locationGetBtnText: {
    fontSize: typography.xs,
    fontWeight: '700',
    color: colours.primaryDark,
  },
  locationClearBtn: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 7,
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: colours.divider,
  },
  locationClearBtnText: {
    fontSize: typography.xs,
    fontWeight: '600',
    color: colours.textMuted,
  },
  kycNote: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.md,
    paddingTop: spacing.xs,
  },
  kycNoteText: {
    fontSize: typography.xs,
    color: colours.textSubtle,
  },
  kycNoteLink: {
    fontSize: typography.xs,
    color: colours.primary,
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
});
